### ISSUE TITLE
COCO20i dataset

### ISSUE THREAD

**Issue by Super-wei** [lizhaoliu-Lec/DENet#16]
Is there a problem with the coco.py file? I use the function run_WrappedCOCOStuff20i to download the COCO dataset, but when it comes to the processing of fold, it always reports an error. Why?Sorry to bother you.

**Comment by lizhaoliu-Lec** [comment]
Can you describe the error with more details?

**Comment by Super-wei** [comment]
In the construct_support_query function in coco.py, the length of unique_cls is always displayed as 0 when running, but it is not clear why

**Comment by lizhaoliu-Lec** [comment]
I suspect that the ``item_class'' cache (in Line 607 coco.py) is not properly dumped. I suggest setting the ``rebuild_pair'' (in Line 535 coco.py) to True to rebuild the ``item_class'' cache file.

**Comment by lizhaoliu-Lec** [comment]
Moreover, do you check the integrity of the downloaded ``(COCO14 in Line 48 coco.py)`` dataset?

**Comment by Super-wei** [comment]
数据集我已经搞好在，在coco.py的946行和952行，应该是root而不是roots吧。但是在我用coco数据集进行训练时，为什么总是报以下错误呢？
Traceback (most recent call last):
  File "E:/paper/DENet-master/train.py", line 32, in <module>
    trainer.train()
  File "E:\paper\DENet-master\trainer\trainers.py", line 222, in train
    plot_idx=plot_idx)
  File "E:\paper\DENet-master\trainer\trainers.py", line 1024, in train_step
    plot_idx=plot_idx)
  File "E:\paper\DENet-master\trainer\trainers.py", line 953, in step
    Ys_full, Yq_full)
  File "E:\paper\DENet-master\trainer\utils.py", line 301, in DENet_forward_wrapper
    outs = model(Is, Ys, Iq, cls_id, **kwargs)
  File "C:\Users\GP\anaconda3\envs\Pytorch_evns_new\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\paper\DENet-master\model\head\denet.py", line 92, in forward
    logits_binary = get_binary_logits(logits_full, label, base=True)
  File "E:\paper\DENet-master\utils\operations.py", line 327, in get_binary_logits
    label_logits = logits_full[torch.arange(logits_full.size(0), device=label.device), label]
IndexError: tensors used as indices must be long, byte or bool tensors
请问你有什么好的修改意见吗？

**Comment by Super-wei** [comment]
Thanks, I have processed the COCO dataset. But I want to modify the network structure of your thesis recently, do you have any good suggestions? Can I chat with you?

**Comment by lizhaoliu-Lec** [comment]
What's in your mind for changing the network architecture? Feel free to contact me via email: 2524463910@qq.com.

**Comment by lizhaoliu-Lec** [comment]
Bug fixed: ``roots -> root``, in coco.py Line 946 and 952.
